### PR TITLE
Added Spark Url

### PR DESCRIPTION
**Pull request by akashsethi24**
If Spark is running on somewhere else other than  local then we need the spark ip configuration for running the code

### CODE REVIEW

**Review by shiv4nsh — COMMENTED** [review]
Could you please change sparkip to SPARK URL so that it would be consistent ! Everything else looks great. Thanks a lot for your contribution :)

**Comment by akashsethi24** [comment]
Just Updated

**Comment by akashsethi24** [comment]
Thanks

**Comment by shiv4nsh** [comment]
@akashsethi24 : Thanks for the contribution :+1:

**Comment by phalodi** [comment]
LGTM!!

**Pull request merged**
